import{FormEvent,useEffect,useState}from'react';
import{Link,useLocation,useNavigate,useOutletContext,useParams,useSearchParams}from'react-router-dom';
import{deleteJson,getJson,postJson}from'./api';
import type{CommunityComment,CommunityPost,CommunityPostDetail,CommunityProfile,Detail,Session}from'./types';
import{AppShell}from'./screens';

type SessionContext={session:Session|null;refreshSession:()=>void};
function useData<T>(path:string,version=0){const[data,setData]=useState<T|null>(null);const[error,setError]=useState('');useEffect(()=>{const c=new AbortController();setData(null);setError('');getJson<T>(path,c.signal).then(setData).catch(e=>{if(e?.name!=='AbortError')setError(e.message)});return()=>c.abort()},[path,version]);return{data,error}}
function time(value:string){return new Intl.DateTimeFormat('bg-BG',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))}

export function CommunityRoot(){return <><CommunityBar/><AppShell/></>}
export function CommunityBar(){const{pathname}=useLocation();const match=pathname.match(/^\/supplier\/([^/]+)\/signals\/([^/]+)/);return <nav className="community-bar" aria-label="Общност"><Link to="/feed">Общност и фийд</Link>{match&&<Link className="community-share" to={`/share/${match[1]}/${match[2]}`}>Сподели този сигнал</Link>}</nav>}

function PostCard({post}:{post:CommunityPost}){return <article className="community-post"><div className="post-meta"><Link to={`/users/${post.author}`}>@{post.author}</Link><time dateTime={post.createdAt}>{time(post.createdAt)}</time></div><p className="opinion-label">Потребителско мнение — не е заключение на TenderLens</p><p className="post-body">{post.body}</p><Link className="signal-reference" to={`/supplier/${post.supplierEik}/signals/${post.signalKey}`}><b>{post.signalName}</b><span>ЕИК {post.supplierEik} · Отвори доказателствата</span></Link><Link className="comments-link" to={`/posts/${post.id}`}>{post.commentCount} коментара</Link></article>}

export function CommunityFeedPage(){const{session}=useOutletContext<SessionContext>();const[search,setSearch]=useSearchParams();const page=Math.max(1,Number(search.get('page')??'1')||1);const{data,error}=useData<CommunityPost[]>(`/api/v1/community/feed?page=${page}&pageSize=20`);return <section className="community-page"><p className="eyebrow">TenderLens общност</p><h1>{session?.authenticated?'Вашият фийд':'Публичен фийд'}</h1><p>{session?.authenticated?'Публикации от вас и профилите, които следвате.':'Последни публични мнения за сигнали за преглед.'}</p>{error&&<p className="error" role="alert">{error}</p>}{!data&&!error&&<p aria-busy="true">Зареждане…</p>}{data?.length===0&&<div className="community-empty"><h2>Все още няма публикации</h2><p>Отворете сигнал за компания и използвайте „Сподели този сигнал“.</p></div>}<div className="community-list">{data?.map(p=><PostCard key={p.id} post={p}/>)}</div>{data&&<PageControls page={page} hasNext={data.length===20} go={next=>setSearch({page:String(next)})}/>}</section>}

export function CommunityProfilePage(){const{username}=useParams();const{session}=useOutletContext<SessionContext>();const[search,setSearch]=useSearchParams();const page=Math.max(1,Number(search.get('page')??'1')||1);const[version,setVersion]=useState(0);const{data,error}=useData<CommunityProfile>(`/api/v1/community/users/${encodeURIComponent(username!)}?page=${page}`,version);const[busy,setBusy]=useState(false);const[actionError,setActionError]=useState('');async function toggle(){if(!session?.authenticated){window.location.href='/login';return}setBusy(true);setActionError('');try{if(data?.isFollowing)await deleteJson(`/api/v1/community/users/${encodeURIComponent(username!)}/follow`);else await postJson(`/api/v1/community/users/${encodeURIComponent(username!)}/follow`,{});setVersion(v=>v+1)}catch(reason){setActionError(reason instanceof Error?reason.message:'Следването не може да бъде променено.')}finally{setBusy(false)}}if(error)return <section className="community-page"><h1>Профилът не може да бъде зареден</h1><p className="error">{error}</p></section>;if(!data)return <section className="community-page" aria-busy="true"><h1>Зареждане на профила…</h1></section>;const own=session?.username?.toLowerCase()===data.username.toLowerCase();return <section className="community-page"><div className="community-profile-head"><div><p className="eyebrow">Публичен профил</p><h1>@{data.username}</h1><p>{data.followers} последователи · следва {data.following}</p></div>{!own&&<button className="primary-button" disabled={busy} onClick={toggle}>{data.isFollowing?'Спри следването':'Следвай'}</button>}</div>{actionError&&<p className="error" role="alert">{actionError}</p>}<h2>Публикации</h2>{data.posts.length===0?<p>Този потребител още не е споделил сигнал.</p>:<div className="community-list">{data.posts.map(p=><PostCard key={p.id} post={p}/>)}</div>}<PageControls page={page} hasNext={data.posts.length===20} go={next=>setSearch({page:String(next)})}/></section>}

function PageControls({page,hasNext,go}:{page:number;hasNext:boolean;go:(page:number)=>void}){return <nav className="pagination" aria-label="Страници с публикации"><button disabled={page===1} onClick={()=>go(page-1)}>Предишна</button><span>Страница {page}</span><button disabled={!hasNext} onClick={()=>go(page+1)}>Следваща</button></nav>}

export function CommunityPostPage(){const{postId}=useParams();const{session}=useOutletContext<SessionContext>();const[search,setSearch]=useSearchParams();const page=Math.max(1,Number(search.get('commentPage')??'1')||1);const[version,setVersion]=useState(0);const{data,error}=useData<CommunityPostDetail>(`/api/v1/community/posts/${postId}?commentPage=${page}&commentPageSize=50`,version);const[body,setBody]=useState('');const[busy,setBusy]=useState(false);const[actionError,setActionError]=useState('');async function submit(e:FormEvent){e.preventDefault();setBusy(true);setActionError('');try{await postJson<CommunityComment>(`/api/v1/community/posts/${postId}/comments`,{body});setBody('');const nextPage=Math.ceil(((data?.commentTotal??0)+1)/50);setSearch({commentPage:String(Math.max(1,nextPage))});setVersion(v=>v+1)}catch(reason){setActionError(reason instanceof Error?reason.message:'Коментарът не може да бъде публикуван.')}finally{setBusy(false)}}if(error)return <section className="community-page"><h1>Публикацията не може да бъде заредена</h1><p className="error">{error}</p></section>;if(!data)return <section className="community-page" aria-busy="true"><h1>Зареждане…</h1></section>;return <section className="community-page"><PostCard post={data.post}/><section className="comments"><h2>Дискусия ({data.commentTotal})</h2>{data.comments.length===0&&<p>Все още няма коментари.</p>}{data.comments.map(c=><article key={c.id} className="comment"><div><Link to={`/users/${c.author}`}>@{c.author}</Link><time dateTime={c.createdAt}>{time(c.createdAt)}</time></div><p>{c.body}</p></article>)}{data.commentTotalPages>1&&<PageControls page={data.commentPage} hasNext={data.commentPage<data.commentTotalPages} go={next=>setSearch({commentPage:String(next)})}/>} {session?.authenticated?<form className="comment-form" onSubmit={submit}><label htmlFor="comment">Добавете аргумент или контекст</label><textarea id="comment" required minLength={1} maxLength={1000} value={body} onChange={e=>setBody(e.target.value)}/>{actionError&&<p className="error" role="alert">{actionError}</p>}<button className="primary-button" disabled={busy}>{busy?'Публикуване…':'Коментирай'}</button></form>:<p><Link to="/login">Влезте</Link>, за да коментирате.</p>}</section></section>}

export function ShareSignalPage(){const{eik,signalKey}=useParams();const{session}=useOutletContext<SessionContext>();const nav=useNavigate();const{data,error}=useData<Detail>(`/api/v1/suppliers/${eik}/signals/${signalKey}?page=1&pageSize=1&sort=value&dir=desc`);const[body,setBody]=useState('');const[submitError,setSubmitError]=useState('');const[busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();if(!session?.authenticated){nav('/login',{state:{from:window.location.pathname}});return}setBusy(true);setSubmitError('');try{const post=await postJson<CommunityPost>('/api/v1/community/posts',{supplierEik:eik,signalKey,body});nav(`/posts/${post.id}`)}catch(reason){setSubmitError(reason instanceof Error?reason.message:'Публикацията не може да бъде създадена.')}finally{setBusy(false)}}return <section className="community-page share-page"><p className="eyebrow">Споделяне за обществен преглед</p><h1>Сподели сигнал</h1>{error&&<p className="error">{error}</p>}{data&&<div className="share-reference"><b>{data.name}</b><span>ЕИК {eik}</span><p>{data.observedFact}</p><Link to={`/supplier/${eik}/signals/${signalKey}`}>Преглед на доказателствата</Link></div>}<form className="share-form" onSubmit={submit}><label htmlFor="post-body">Защо смятате, че сигналът заслужава внимание?</label><textarea id="post-body" required minLength={1} maxLength={1200} value={body} onChange={e=>setBody(e.target.value)} placeholder="Опишете наблюдението си с неутрален език и посочете какво трябва да се провери."/><small>{body.length}/1200 · Това е публично потребителско мнение.</small>{submitError&&<p className="error" role="alert">{submitError}</p>}<button className="primary-button" disabled={busy||!data||session===null}>{busy?'Публикуване…':session===null?'Зареждане на профила…':'Публикувай във фийда'}</button></form></section>}
